### ISSUE TITLE
problem with system settings and colours

### ISSUE THREAD

**Issue by mashrit** [Bali10050/Lightly#29]
i installed this theme and wanted the glassy blurred look

so, i installed the [glassly](https://store.kde.org/p/1652008) colour scheme and when i opened the system settings,this happened

![image](https://github.com/user-attachments/assets/9de51be0-1736-4198-bc2f-56379610370c)

btw love that someone is finally maintaining(and improving) this theme

**Comment by Bali10050** [comment]
It seems like all lightly forks have this issue, so there's no quick fix that I can provide. It seems like it only happens on wayland, so if you want to use it on x11, you can. The best piece of info I could find is that it happens when `[Colors:Window]` has a `BackgroundNormal` with transparency bellow 100. If you have trouble changing your settings back, you can use [`uninstall.sh`](https://github.com/Bali10050/Lightly/blob/qt6/uninstall.sh), but you need to set it executable, and use sudo to run it, then kde should use the default breeze theme as a fallback, which doesn't have this problem. Sorry for the inconvenience.

**Comment by DeltaCopy** [comment]
What is strange is that after I use `kcmshell6 kcm_landingpage` from the terminal then `systemsettings` opens as expected.
Both sidebar and content window to the right are visible.

**Comment by mashrit** [comment]
>The best piece of info I could find is that it happens when `[Colors:Window]` has a `BackgroundNormal` with transparency bellow 100.

according to my own research it seems that any transparency value below 255 triggers this

**Comment by DeltaCopy** [comment]
> according to my own research it seems that any transparency value below 255 triggers this

In the src lightlystyle.cpp there is a blur effect being applied with a condition to check if `widget->palette().color( widget->backgroundRole() ).alpha() < 255 ` - this part may need updating.

**Comment by DeltaCopy** [comment]
I don't have a proper solution to this.
However, here are my findings.

**Tested on Archlinux | Plasma 6.2.1**

Firstly, the issue seems to be around the blurring of windows.
Specifically the lines:

https://github.com/Bali10050/Lightly/blob/qt6/kstyle/lightlyblurhelper.cpp#L176
https://github.com/Bali10050/Lightly/blob/qt6/kstyle/lightlyblurhelper.cpp#L177

The alpha channel of this color scheme has a value of 220 - `BackgroundNormal=30,32,36,220` inside `[Colors:Window]`
Commenting out those 2 lines opens `systemsettings` using the Glassly-Darker color scheme. 

@mashrit please send info on distro and Plasma version.

**Comment by mashrit** [comment]
I am using EndeavourOs 
plasma version: 6.2.1
qt version 6.8.0

**Comment by DeltaCopy** [comment]
Does switching the backend render mode to software help ?

`kcmshell6 kcm_qtquicksettings`
Render Backend: Software

**Comment by mashrit** [comment]
> Does switching the backend render mode to software help ?
> 
> `kcmshell6 kcm_qtquicksettings` Render Backend: Software

yes, this works

**Comment by mashrit** [comment]
![ok](https://github.com/user-attachments/assets/38ce85eb-9f9a-4565-8a4f-1fc1f29a8689)

now there is this issue, so images are being drawn at the corner

**Comment by DeltaCopy** [comment]
> now there is this issue, so images are being drawn at the corner

Not too sure maybe try resizing the window to repaint the window.

Be advised that if you use software rendering it will ultimately use your CPU for rendering rather than the GPU.
It is not a permanent solution.

The following has been tested.
Using the Glassly-Darker color scheme.

**With no changes to the backend renderer.**

EndeavourOS
Plasma 6.1.5
QT 6.7.2
**Works**

EndeavourOS
Plasma 6.2.1
QT 6.8.0
**Doesn't work**

Fedora 40
Plasma 6.2.1
QT 6.7.2
**Works**

@Bali10050 this issue is due to whatever changes that have been made in QT 6.8.0
https://doc.qt.io/qt-6/whatsnew68.html#qt-quick-controls-module

**Comment by christiantosta** [comment]
Problem not occurs with [Vinyl](https://github.com/ekaaty/vinyl-theme) that is a Lightly fork.

Fedora: 40
Plasma: 6.2.1
Frameworks: 6.7.0
Qt: 6.7.2

![vinyl_6 1 6-glassy](https://github.com/user-attachments/assets/2b866b61-5d28-4945-9028-3400b4a2759b)

**Comment by Bali10050** [comment]
I'm not sure if I'm hallucinating or not, but 532779d seems to fix this issue

**Comment by mashrit** [comment]
> I'm not sure if I'm hallucinating or not, but [532779d](https://github.com/Bali10050/Lightly/commit/532779db035def3dd99917a4194c3eb40c69c4f6) seems to fix this issue

we both might be hallucinating then

**Comment by christiantosta** [comment]
> I'm not sure if I'm hallucinating or not, but [532779d](https://github.com/Bali10050/Lightly/commit/532779db035def3dd99917a4194c3eb40c69c4f6) seems to fix this issue

Looks like a reversion of a previous patch. But lines 142/143 are redundant, no? On Vinyl, codes looks as below:


``` cpp
                // cast to widget and check
                QWidget* widget(qobject_cast<QWidget*>(object));

                if (!widget)
                    break;

                update(widget);
                break;
            }

...

                // blur entire window
                if( widget->palette().color( QPalette::Window ).alpha() < 255 )
                    return roundedRegion(rect, StyleConfigData::cornerRadius(), false, false, true, true);
                
                // blur specific widgets
                QRegion region;
```

But I prefer to use kwin effects to blur them via Lightly/Vinyl.

**Comment by DeltaCopy** [comment]
> But lines 142/143 are redundant, no?

Yes now redundant code.
